### ISSUE TITLE
How to declare realm setting in lib/myapp.pm

### ISSUE THREAD

**Issue by aaryabhatt** [yxes/Yxes-Catalyst-Authentication-Credential-Google#1]
Hi Yxes, 

Thanks for writing such a simple and nice module for gmail authentication, this is the only module by which I was able to login with gmail.  Now my question is, how I can declare realm setting of myapp.conf file in lib/myapp.pm file, I need it because, I am using facbook authentication and my databse authentication. My default realm is something else.
## 

Thanks
Amit Bondwal

**Comment by yxes** [comment]
It's great to hear that someone else found this useful. It was a real struggle for me as Google doesn't implement oAuth2 in the same way as everyone else. I haven't looked at this code in a long time but it inherits [Catalyst::Plugin::Authentication](http://search.cpan.org/~bobtfish/Catalyst-Plugin-Authentication-0.10023/lib/Catalyst/Plugin/Authentication.pm) which handles the realms portion.

specifically: [Authentication Realms](http://search.cpan.org/~bobtfish/Catalyst-Plugin-Authentication-0.10023/lib/Catalyst/Plugin/Authentication.pm#Realms)

Example lifted from Catalyst::Plugin::Authentication

> the default realm is checked, but we could just as easily check an alternate realm. If this were an admin login, for example, we could authenticate on the admin realm by simply changing the `$c->authenticate()` call:

``` perl
if ( $c->authenticate( { username => $user, password => $password }, 'admin' ) ) {
        $c->res->body( "hello " . $c->user->get("name") );
} 
```

In the above case, they are using _admin_ as the realm and overriding the default.

Hope that helps :)
